"""The shipped schema corpus is the only source of schema definitions.

A copy of a shipped schema under ``tests/`` is a restatement: the served path
reads ``configs/schemas/``, nobody edits the copy, and a field added to the
shipped definition never reaches the test. That is how the ensemble suite came
to load a ``video_colpali_smol500_mv_frame`` with no ``document_mapping`` while
production shipped one declaring ``id: video_id``.

Tests point their schema loader at ``configs/schemas``; a test-owned schema is
allowed only for a name the shipped corpus does not define.
"""

import json
from pathlib import Path

import pytest

pytestmark = [pytest.mark.unit, pytest.mark.ci_fast]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_SHIPPED = _REPO_ROOT / "configs" / "schemas"

# Derived from the schema corpus at run time (gitignored, auto-generated by
# StrategyAwareProcessor); a committed copy of it is a restatement too.
_DERIVED = "ranking_strategies.json"

_SELF = Path(__file__).name


def restated_schema_files(tests_root: Path, shipped_names: set[str]) -> list[str]:
    """Names under ``tests_root`` that restate a shipped or derived corpus file."""
    return sorted(
        str(p.relative_to(tests_root))
        for p in tests_root.rglob("*.json")
        if p.name in shipped_names or p.name == _DERIVED
    )


def private_schema_loader_dirs(tests_root: Path) -> list[str]:
    """Test modules that build a schema loader over a private schema directory."""
    offenders = []
    for p in tests_root.rglob("*.py"):
        if p.name == _SELF:
            continue
        text = p.read_text(errors="replace")
        if "FilesystemSchemaLoader(" not in text:
            continue
        if "resources/schemas" in text:
            offenders.append(str(p.relative_to(tests_root)))
    return sorted(offenders)


def _shipped_names() -> set[str]:
    return {p.name for p in _SHIPPED.glob("*_schema.json")}


def test_shipped_corpus_defines_the_video_profile_under_test():
    shipped = _shipped_names()
    assert "video_colpali_smol500_mv_frame_schema.json" in shipped
    assert "image_colpali_mv_schema.json" in shipped
    assert "video_colqwen_omni_mv_chunk_30s_schema.json" in shipped


def test_shipped_video_profile_declares_its_source_identity_field():
    """The field whose absence from the copy broke every ensemble search."""
    schema = json.loads(
        (_SHIPPED / "video_colpali_smol500_mv_frame_schema.json").read_text()
    )
    assert schema["document_mapping"]["id"] == "video_id"


def test_shipped_video_profile_resolves_a_source_identity_at_the_search_path():
    """The production helper that raised on the restated copy.

    ``_schema_source_identity_field(..., required=True)`` is what every
    source-granularity search calls; it raised "declares no
    document_mapping.id" for the whole ensemble suite because the loader read
    a copy without the mapping. Drive the real loader over the shipped corpus
    and the real helper over what it returns.
    """
    from cogniverse_core.schemas.filesystem_loader import FilesystemSchemaLoader
    from cogniverse_vespa.search_backend import _schema_source_identity_field

    loader = FilesystemSchemaLoader(_SHIPPED)
    name = "video_colpali_smol500_mv_frame"
    assert (
        _schema_source_identity_field(
            loader.load_schema(name), schema_name=name, required=True
        )
        == "video_id"
    )

    stripped = {
        k: v for k, v in loader.load_schema(name).items() if k != "document_mapping"
    }
    with pytest.raises(ValueError, match="declares no document_mapping.id"):
        _schema_source_identity_field(stripped, schema_name=name, required=True)


def test_no_shipped_schema_is_restated_under_tests():
    assert restated_schema_files(_REPO_ROOT / "tests", _shipped_names()) == []


def test_no_test_builds_a_loader_over_a_private_schema_dir():
    assert private_schema_loader_dirs(_REPO_ROOT / "tests") == []


def test_detectors_fire_on_synthetic_offenders(tmp_path):
    """The two detectors above go red on a constructed offender.

    A repository-wide "no offenders remain" assertion cannot protect its own
    detector: once the tree is clean, gutting the detector leaves it green.
    """
    tests_root = tmp_path / "tests"
    (tests_root / "system" / "resources" / "schemas").mkdir(parents=True)
    (
        tests_root / "system" / "resources" / "schemas" / "video_x_schema.json"
    ).write_text("{}")
    (tests_root / "system" / "resources" / "schemas" / _DERIVED).write_text("{}")
    (tests_root / "unmirrored_schema.json").write_text("{}")
    (tests_root / "test_uses_private_dir.py").write_text(
        'FilesystemSchemaLoader(base_path=Path("tests/system/resources/schemas"))\n'
    )
    (tests_root / "test_uses_shipped_dir.py").write_text(
        'FilesystemSchemaLoader(base_path=Path("configs/schemas"))\n'
    )

    assert restated_schema_files(tests_root, {"video_x_schema.json"}) == [
        "system/resources/schemas/ranking_strategies.json",
        "system/resources/schemas/video_x_schema.json",
    ]
    assert private_schema_loader_dirs(tests_root) == ["test_uses_private_dir.py"]
