[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cogniverse"
version = "0.1.0"
description = "Multi-agent RAG system for video content analysis"
authors = [{name = "Cogniverse Team"}]
requires-python = ">=3.8"
dependencies = [
    "cogniverse-core>=0.1.0",
    "cogniverse-app>=0.1.0",
    "cogniverse-vespa-backend>=0.1.0",
    "cogniverse-evaluation>=0.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=22.0.0",
    "ruff>=0.1.0",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[tool.setuptools.package-data]
"*" = ["*.json", "*.yaml", "*.yml", "*.toml"]

# Development mode installation (for editable installs)
[tool.pip-tools]
extra-packages = [
    "-e ./src/common",
    "-e ./src/app", 
    "-e ./src/backends/vespa",
    "-e ./src/evaluation",
]