evaluation:
  name: "Cogniverse Video RAG Evaluation v1"
  
  datasets:
    - name: "video_queries_v1"
      path: "data/eval/video_queries.json"
      type: "retrieval"
      phoenix_dataset: true
    
    - name: "temporal_queries_v1"
      path: "data/eval/temporal_queries.json"
      type: "temporal"
    
    - name: "multimodal_alignment_v1"
      path: "data/eval/multimodal_pairs.json"
      type: "alignment"
  
  profiles:
    - frame_based_colpali
    - direct_video_global
    - direct_video_global_large
  
  strategies:
    - float_float
    - binary_binary
    - hybrid_binary_bm25
    - phased
  
  metrics:
    retrieval:
      - mrr
      - ndcg_at_1
      - ndcg_at_5
      - ndcg_at_10
      - precision_at_1
      - precision_at_5
      - precision_at_10
      - recall_at_1
      - recall_at_5
      - recall_at_10
    
    performance:
      - latency_p50
      - latency_p95
      - latency_p99
      - throughput_qps
      - memory_usage_mb
  
  inspect_tasks:
    - video_retrieval_accuracy
    - temporal_understanding
    - multimodal_alignment
    - failure_analysis
  
  phoenix:
    instrumentation:
      enabled: true
      components:
        - video_pipeline
        - search_backends
        - query_encoders
        - agents
    
    monitoring:
      enabled: true
      alert_thresholds:
        latency_p95_ms: 1000
        error_rate: 0.05
        mrr_drop: 0.1
        throughput_drop: 0.3
    
    dataset_management:
      versioning: true
      auto_link_traces: true
      batch_evaluation: true
    
    experiments:
      parallel_runs: true
      timeout_seconds: 300
      batch_size: 10
  
  inspect:
    parallel_tasks: true
    save_logs: true
    log_dir: "outputs/inspect_logs"
    model: "cogniverse"
  
  reporting:
    generate_html: true
    generate_markdown: true
    include_visualizations: true
    export_traces: true
    
  ci_cd:
    enabled: false
    trigger_on_commit: true
    regression_threshold: 0.05
    required_pass_rate: 0.95