"""The deployed web client's Optimization framework view against the e2e cluster.

Each test drives the page and reads its outcome back from the live runtime:
search annotations harvested from the web tenant's own searches, the golden
dataset they build, a synthetic run generated by the cluster's optimizer pod
and routed into the approval store, a module optimization run in Argo, and
the XGBoost profile recommender trained on the tenant's spans.
"""

from __future__ import annotations

import re
import time

import httpx
import pytest
from playwright.sync_api import Page, expect

from cogniverse_foundation.common.tenant_utils import canonical_tenant_id
from tests.e2e.cluster import RUNTIME
from tests.e2e.conftest import GATEWAY_VIDEO_QUERIES
from tests.e2e.tenants import register_tenant_and_wait, unique_id
from tests.e2e.test_api_e2e import PROFILE

pytestmark = [pytest.mark.e2e, pytest.mark.browser]


def _web():
    """The deployed web client's e2e helpers, ``tests/e2e/web_client.py``."""
    from tests.e2e import web_client

    return web_client


VIEW_ID, VIEW_LABEL = "optimization-framework", "Optimization framework"
# Span export is batched and Phoenix indexes annotations shortly after a write.
SPAN_SETTLE_S = 300.0
# A synthetic run starts a pod, samples the backend and generates with the
# cluster's LM; the suite's batch optimization runs allow this long.
SYNTHETIC_RUN_TIMEOUT_S = 1800.0
MODULE_RUN_TIMEOUT_S = 1800.0
SETTLED = ("Succeeded", "Failed", "Error")


@pytest.fixture(scope="module")
def web_corpus() -> str:
    return _web().ensure_web_tenant_corpus()


def _open(page: Page, tenant: str, tab: str) -> None:
    page.goto(f"{_web().WEB}/#/ops/{VIEW_ID}", timeout=_web().VIEW_TIMEOUT_MS)
    expect(page.get_by_role("heading", name=VIEW_LABEL, level=1)).to_be_visible(
        timeout=_web().VIEW_TIMEOUT_MS
    )
    _web().choose_tenant(page, tenant, "Open")
    page.get_by_role("navigation", name="Optimization sections").get_by_role(
        "button", name=tab, exact=True
    ).click()


def _runtime(method: str, path: str, **kwargs) -> dict:
    response = httpx.request(method, f"{RUNTIME}{path}", timeout=600.0, **kwargs)
    assert response.status_code == 200, response.text
    return response.json()


def _search(tenant: str, query: str) -> None:
    _runtime(
        "POST",
        "/search/",
        json={
            "query": query,
            "profile": PROFILE,
            "strategy": "default",
            "top_k": 5,
            "tenant_id": tenant,
        },
    )


def _until(read, done, timeout: float, interval: float = 5.0):
    deadline = time.monotonic() + timeout
    value = read()
    while not done(value):
        assert time.monotonic() < deadline, value
        time.sleep(interval)
        value = read()
    return value


def _settled_run(tenant: str, name: str, timeout: float) -> dict:
    return _until(
        lambda: _runtime("GET", f"/admin/tenant/{tenant}/optimize/runs/{name}"),
        lambda status: status["phase"] in SETTLED,
        timeout,
        interval=15.0,
    )


class TestSearchAnnotationsAndGoldenDataset:
    def test_a_rated_search_is_stored_and_builds_the_golden_dataset(
        self, page, web_corpus
    ):
        query = f"{GATEWAY_VIDEO_QUERIES[0]} {unique_id('annotate')}"
        _search(_web().WEB_TENANT, query)
        searches_path = (
            f"/admin/tenant/{_web().WEB_TENANT}/search-annotations?lookback_hours=1"
        )
        listed = _until(
            lambda: _runtime("GET", searches_path)["searches"],
            lambda searches: any(s["query"] == query for s in searches),
            SPAN_SETTLE_S,
        )
        search = next(s for s in listed if s["query"] == query)

        _open(page, _web().WEB_TENANT, "Search annotations")
        page.get_by_label("Annotation type").select_option("stars")
        fetch = page.get_by_role("form", name="Fetch searches")
        fetch.get_by_label("Lookback hours").fill("1")
        fetch.get_by_role("button", name="Fetch search results").click()
        expect(page.get_by_role("status").filter(has_text="Fetched")).to_have_text(
            re.compile(r"^Fetched \d+ search results\.$"),
            timeout=_web().VIEW_TIMEOUT_MS,
        )
        queue = page.get_by_role("region", name=re.compile(r"^Annotation queue"))
        page_select = queue.get_by_label("Page")
        card = queue.get_by_role(
            "group", name=re.compile(rf": {re.escape(query[:80])}$")
        )
        for option in page_select.locator("option").all_inner_texts():
            page_select.select_option(option)
            if card.count():
                break
        card.locator("summary").click()
        assert _web().facts(card.locator("dl").first)["Profile"] == (
            search["profile"] or "N/A"
        )
        expect(card.get_by_role("list", name="Top results").locator("li")).to_have_text(
            search["results"]
        )
        rating = card.get_by_role("form", name="Your annotation")
        rating.get_by_label("Rating").fill("5")
        rating.get_by_label("Notes (optional)").fill("e2e golden")
        rating.get_by_role("button", name="Save rating").click()
        expect(rating.get_by_role("status").filter(has_text="Saved")).to_have_text(
            "Saved: 5 stars", timeout=_web().VIEW_TIMEOUT_MS
        )

        annotated = _until(
            lambda: next(
                s
                for s in _runtime("GET", searches_path)["searches"]
                if s["query"] == query
            )["annotation"],
            lambda annotation: annotation is not None,
            SPAN_SETTLE_S,
        )
        assert annotated == {
            "label": "positive",
            "score": 1.0,
            "annotation_type": "stars",
            "notes": "e2e golden",
        }

        page.get_by_role("navigation", name="Optimization sections").get_by_role(
            "button", name="Golden dataset"
        ).click()
        build = page.get_by_role("form", name="Build golden dataset")
        build.get_by_label("Lookback days").fill("1")
        build.get_by_role("button", name="Build golden dataset").click()
        expected = _runtime(
            "POST",
            f"/admin/tenant/{_web().WEB_TENANT}/golden-dataset",
            json={"min_rating": 0.8, "lookback_days": 1},
        )["dataset"]
        expect(page.get_by_role("status").filter(has_text="Built")).to_have_text(
            f"Built a golden dataset of {len(expected)} queries.",
            timeout=_web().RUN_TIMEOUT_MS,
        )
        if search["results"]:
            assert query in expected
            sample = page.get_by_role("table", name="Golden dataset sample")
            rows = [
                row.locator("td").all_inner_texts()
                for row in sample.locator("tbody tr").all()
            ]
            assert rows == [
                [q, str(len(entry["expected_videos"])), f"{entry['avg_relevance']:.2f}"]
                for q, entry in list(expected.items())[:10]
            ]


class TestSyntheticRun:
    def test_a_generated_run_is_followed_to_its_reviewed_examples(
        self, page, web_corpus
    ):
        _open(page, _web().WEB_TENANT, "Synthetic data")
        form = page.get_by_role("form", name="Generate synthetic data")
        form.get_by_label("Optimizer", exact=True).select_option("query_enhancement")
        form.get_by_label("Examples to generate").fill("2")
        form.get_by_label("Backend sample size").fill("20")
        form.get_by_role("button", name="Generate synthetic data").click()
        notice = form.get_by_role("status")
        expect(notice).to_contain_text(
            "Generating 2 examples for query_enhancement: ",
            timeout=_web().VIEW_TIMEOUT_MS,
        )
        name = re.fullmatch(
            r"Generating 2 examples for query_enhancement: (\S+)\.", notice.inner_text()
        ).group(1)
        status = _settled_run(_web().WEB_TENANT, name, SYNTHETIC_RUN_TIMEOUT_S)
        results = _runtime(
            "GET", f"/admin/tenant/{_web().WEB_TENANT}/optimize/runs/{name}/synthetic"
        )
        assert (results["settled"], results["parameters"]["count"]) == (True, 2), (
            results
        )
        [outcome] = results["outcomes"]

        region = page.get_by_role("region", name=f"Results of {name}")
        shown = region.get_by_role("region", name="Outcome for query_enhancement")
        if outcome["status"] == "success":
            expect(shown.get_by_role("status").first).to_have_text(
                f"Generated {outcome['examples_generated']} examples: "
                f"{outcome['auto_approved']} auto-approved, "
                f"{outcome['pending_review']} awaiting review.",
                timeout=_web().RUN_TIMEOUT_MS,
            )
            assert outcome["examples_generated"] == 2, outcome
            assert _web().facts(
                shown.get_by_role("definition").first.locator("..")
            ) == {
                "Auto-approved": str(outcome["auto_approved"]),
                "Pending review": str(outcome["pending_review"]),
                "Average confidence": f"{outcome['avg_confidence']:.2f}",
            }
            pending = {
                item["item_id"]
                for item in _runtime(
                    "GET", f"/admin/tenant/{_web().WEB_TENANT}/approvals"
                )["items"]
                if item["batch_id"] == outcome["batch_id"]
            }
            assert pending == {
                item["item_id"]
                for item in outcome["items"]
                if item["status"] == "pending_review"
            }
        else:
            assert status["phase"] in ("Failed", "Error"), status
            expect(shown.get_by_role("alert")).to_have_text(
                f"Generation for query_enhancement failed: {outcome['error']}",
                timeout=_web().RUN_TIMEOUT_MS,
            )


class TestModuleOptimization:
    def test_a_workflow_module_run_carries_its_options_to_argo(self, page):
        tenant = canonical_tenant_id(unique_id("webmodule"))
        register_tenant_and_wait(tenant, created_by="e2e")
        _open(page, tenant, "Module optimization")
        form = page.get_by_role("form", name="Optimize a module")
        form.get_by_label("Module to optimize").select_option("workflow")
        form.get_by_label("Max iterations").fill("1")
        form.get_by_label("Lookback hours").fill("1")
        form.get_by_role("button", name="Submit module optimization").click()
        submitted = page.get_by_role(
            "region", name=re.compile(r"^Run manual-optimize-workflow-")
        )
        expect(submitted.get_by_role("status")).to_contain_text(
            "Submitted manual-optimize-workflow-", timeout=_web().VIEW_TIMEOUT_MS
        )
        name = (
            submitted.get_by_role("status")
            .inner_text()
            .removeprefix("Submitted ")
            .rstrip(".")
        )
        runs = _runtime("GET", f"/admin/tenant/{tenant}/optimize/runs")["runs"]
        assert [(run["workflow_name"], run["mode"]) for run in runs] == [
            (name, "workflow")
        ]
        status = _settled_run(tenant, name, MODULE_RUN_TIMEOUT_S)
        # A tenant without orchestration spans has nothing to optimize, which
        # the CLI reports as no_data and exits 0.
        assert status["phase"] == "Succeeded", status
        expect(submitted.locator("dt:text-is('Phase') + dd")).to_have_text(
            "Succeeded", timeout=_web().RUN_TIMEOUT_MS
        )


class TestProfileSelectionAndMetrics:
    def test_the_recommender_and_the_metrics_show_what_the_runtime_holds(
        self, page, web_corpus
    ):
        for query in GATEWAY_VIDEO_QUERIES:
            _search(_web().WEB_TENANT, query)
        _open(page, _web().WEB_TENANT, "Profile selection")
        analyze = page.get_by_role("form", name="Analyze search spans")
        analyze.get_by_label("Lookback days").fill("1")
        analyze.get_by_role("button", name="Analyze search spans").click()
        expect(page.get_by_role("status").filter(has_text="search spans")).to_have_text(
            re.compile(r"^Found \d+ search spans\.$"), timeout=_web().RUN_TIMEOUT_MS
        )
        shown = int(
            re.search(
                r"\d+",
                page.get_by_role("status").filter(has_text="search spans").inner_text(),
            ).group()
        )
        analysis = _runtime(
            "GET",
            f"/admin/tenant/{_web().WEB_TENANT}/profile-selection/analysis?lookback_days=1",
        )
        assert shown == analysis["search_spans"]

        training = page.get_by_role("region", name="Train profile selector")
        training.get_by_role("button", name="Train profile selector model").click()
        expect(
            training.get_by_role("status")
            .filter(has_text="Model trained")
            .or_(training.get_by_role("alert"))
        ).to_be_visible(timeout=_web().RUN_TIMEOUT_MS)
        model = _runtime(
            "GET", f"/admin/tenant/{_web().WEB_TENANT}/profile-selection/model"
        )
        if training.get_by_role("alert").count():
            expect(training.get_by_role("alert")).to_have_text(
                re.compile(r"^Training failed: Cannot train the recommender: ")
            )
        else:
            assert model["trained"] is True
            expect(
                training.get_by_role("status").filter(has_text="Model trained")
            ).to_contain_text(f"({', '.join(model['profiles'])}).")

        page.get_by_role("navigation", name="Optimization sections").get_by_role(
            "button", name="Metrics"
        ).click()
        metrics = _runtime(
            "GET",
            f"/admin/tenant/{_web().WEB_TENANT}/optimization-metrics?lookback_days=7",
        )
        if metrics["routing"]:
            panel = page.get_by_role("region", name="Routing optimization metrics")
            expect(panel.locator("dt:text-is('Total decisions') + dd")).to_have_text(
                re.compile(r"^\d+$"), timeout=_web().RUN_TIMEOUT_MS
            )
            agents = [
                row.locator("td").first.inner_text()
                for row in panel.get_by_role("table", name="Per-agent performance")
                .locator("tbody tr")
                .all()
            ]
            assert agents == [
                agent["agent"] for agent in metrics["routing"]["per_agent"]
            ]

        page.get_by_role("navigation", name="Optimization sections").get_by_role(
            "button", name="Reranking"
        ).click()
        panel = page.get_by_role("region", name="Reranking optimization")
        current = panel.locator("dt:text-is('Current annotations') + dd")
        expect(current).to_have_text(
            re.compile(r"^\d+$"), timeout=_web().VIEW_TIMEOUT_MS
        )
        count = _runtime(
            "GET",
            f"/admin/tenant/{_web().WEB_TENANT}/search-annotations/count?lookback_days=90",
        )["annotated_searches"]
        assert int(current.inner_text()) == count
