version: '3.8'

services:
  # Phoenix for evaluation and observability
  phoenix:
    container_name: cogniverse-phoenix
    build:
      context: ./phoenix
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    environment:
      - PHOENIX_PORT=6006
      - PHOENIX_HOST=0.0.0.0
      - PHOENIX_WORKING_DIR=/data
      - PHOENIX_MAX_TRACES=100000
      - PHOENIX_ENABLE_PROMETHEUS=true
      - PHOENIX_ENABLE_CORS=true
    volumes:
      - phoenix-data:/data
      - ../data/phoenix:/phoenix-backup
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - cogniverse-net

  # Vespa for search backend
  vespa:
    container_name: cogniverse-vespa
    image: vespaengine/vespa:latest
    ports:
      - "8080:8080"  # HTTP API
      - "19071:19071"  # Config server
    environment:
      - VESPA_CONFIGSERVERS=vespa
    volumes:
      - vespa-data:/opt/vespa/var
      - ../configs/schemas:/opt/vespa/schemas:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:19071/state/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - cogniverse-net

  # Modal stub server for VLM (development only)
  modal-stub:
    container_name: cogniverse-modal-stub
    build:
      context: ./modal-stub
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODAL_ENV=local
    volumes:
      - ../data/cache:/app/cache
    restart: unless-stopped
    networks:
      - cogniverse-net
    profiles:
      - development

  # Cogniverse application
  cogniverse:
    container_name: cogniverse-app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    ports:
      - "8501:8501"  # Streamlit UI
      - "8502:8502"  # API
    environment:
      # Phoenix connection
      - PHOENIX_URL=http://phoenix:6006
      - PHOENIX_ENABLED=true
      
      # Vespa connection
      - VESPA_URL=http://vespa:8080
      - VESPA_PORT=8080
      
      # Application settings
      - VIDEO_PROFILE=frame_based_colpali
      - LOG_LEVEL=INFO
      
    volumes:
      # Code (for development)
      - ../src:/app/src:ro
      - ../configs:/app/configs:ro
      - ../scripts:/app/scripts:ro
      
      # Data volumes
      - ../data/videos:/app/data/videos
      - ../data/testset:/app/data/testset:ro
      - ../outputs:/app/outputs
      
      # Cache
      - cache-data:/app/.cache
      
    depends_on:
      - phoenix
      - vespa
    restart: unless-stopped
    networks:
      - cogniverse-net

volumes:
  phoenix-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../data/phoenix
      o: bind
  
  vespa-data:
    driver: local
  
  cache-data:
    driver: local

networks:
  cogniverse-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16